# Generated by Django 2.0.3 on 2018-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(max_length=140)),
                ('hashtags', models.CharField(max_length=140)),
            ],
        ),
    ]
