# Generated by Django 2.0.3 on 2018-04-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0002_auto_20180403_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
