# Generated by Django 2.0.3 on 2018-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0005_auto_20180407_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id_number',
            field=models.CharField(max_length=18),
        ),
    ]
