# Generated by Django 2.0.3 on 2018-04-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0006_auto_20180407_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
