# Generated by Django 2.0.3 on 2018-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0007_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=100, verbose_name='Please enter a keyword :'),
        ),
    ]
