# Generated by Django 2.0.3 on 2018-05-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0009_auto_20180527_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
