# Generated by Django 2.0.3 on 2018-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0012_auto_20180527_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(default='DEFAULT VALUE', max_length=100, verbose_name='Please enter a keyword :'),
        ),
        migrations.AlterField(
            model_name='relevanttweet',
            name='link',
            field=models.CharField(default='DEFAULT VALUE', max_length=60),
        ),
    ]
