# Generated by Django 2.0.3 on 2018-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0013_auto_20180527_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_mentions',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
