# Generated by Django 2.1.2 on 2018-10-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0017_relevanttweet_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevanttweet',
            name='text',
        ),
    ]
