# Generated by Django 2.1.2 on 2018-10-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitmining', '0020_auto_20181020_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='language',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
